name: Release

on:
  push:
    branches: [ main ]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write

    steps:
    - uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
      with:
        fetch-depth: 0
        persist-credentials: false

    - uses: whitphx/scriv-release@591fbdc73d28e1fc559c92ead1e227f7aa05b2fa # v0.7.0
      with:
        client-id: ${{ vars.RELEASE_APP_CLIENT_ID }}
        app-private-key: ${{ secrets.RELEASE_APP_KEY }}
